name: "Issue Tracker Stuff"
description: "Does Issue Tracker Things"
author: "Charles Bock <Charles@CharlesBock.com>"
branding:
  icon: star
  color: purple
inputs:
  repo-token:
    description: "token"
    required: true
  repo:
    description: "repo name"
    required: true
  pointslabel:
    description: "pattern to detect the countable points label"
    required: true
    default: "points"
  outputfile:
      description: "pattern to detect the countable points label"
      required: false
      default: docs/pointscount.md
outputs:
  pointscount:
    description: 'The total points counted'
runs:
  using: "node12"
  main: "index.js"
